"""
Django settings for settings project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from oauth2_provider import settings as oauth2_settings

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.conf import settings
import os
import pymysql
pymysql.install_as_MySQLdb()
import dj_database_url
from dotenv import load_dotenv
load_dotenv() # Loads variables from .env into os.enviro


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False




# Application definition

INSTALLED_APPS = [

    "unfold",  # before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # 'storages',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_hotp',
    'django_otp.plugins.otp_static',
    'rest_framework',
    'rest_framework.authtoken',
    "social_django",
    'oauth2_provider',
    "rest_framework_simplejwt",  # simpleJwt Authentication
    'django_extensions',
    # 'two_factor',
    "corsheaders",
    'django_filters',
    'nextCart',
    'authUser',
    'portfolio',
   

]

# TWO_FACTOR_WEBAUTHN_RP_NAME = "NextCart"



AUTH_USER_MODEL = 'nextCart.User'  # Replace 'nextCart' with the app where the custom User model is defined

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    # Others auth providers (e.g. Facebook, OpenId, etc)
    # Google  OAuth2
    'social_core.backends.google.GoogleOAuth2',
    # drf-social-oauth2
    'drf_social_oauth2.backends.DjangoOAuth2',
    # Django
    'rest_framework.authentication.TokenAuthentication',
    'oauth2_provider.backends.OAuth2Backend',
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # JWT Authentication
        'rest_framework.authentication.TokenAuthentication',         
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.SessionAuthentication',
        'drf_social_oauth2.authentication.SocialAuthentication',  
            
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    
}

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 30  # Show 30 results per page
}




OAUTH2_PROVIDER = { 
    'ACCESS_TOKEN_EXPIRE_SECONDS': 36000, 
    'REFRESH_TOKEN_EXPIRE_SECONDS': 1209600, 
    'AUTHORIZATION_CODE_EXPIRE_SECONDS': 600, 
    }

# Google configuration
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')

# expires in 6 months
oauth2_settings.DEFAULTS["ACCESS_TOKEN_EXPIRE_SECONDS"]

# Define SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE to get extra permissions from Google.
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add this right after SecurityMiddleware
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]


SITE_ID = 1



ROOT_URLCONF = 'settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, 'templates') ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'settings.wsgi.application'



#  Gmail Configuration

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL')


# Database Configuration


# RDS Database Configuration
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.environ.get("DB_NAME"),
#         "USER": os.environ.get("DB_USER"),
#         "PASSWORD": os.environ.get("DB_PASSWORD"),
#         "HOST": os.environ.get("DB_HOST"),
#         "PORT": os.environ.get("DB_PORT"),
#         # "OPTIONS": {
#         #     "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
#         #     "charset" : "utf8mb4",
#         # },
#         # For connection management in production (Optional)
#         # "CONN_MAX_AGE": 600,
#     }
#     }

# Supabase Database Configuration
db_url = os.environ.get('DATABASE_URL')
DATABASES = {
    'default': dj_database_url.config(
            default=db_url,
            conn_max_age=0,
            ssl_require=True
        )
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = "/static/"
MEDIA_URL = "/media/"

# Add this line

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] 

# Add this line
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


# Add this line
MEDIA_ROOT = os.path.join(BASE_DIR, "mediafiles")







# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# ALLOWED_HOSTS = ['13.62.196.86', 'ec2-13-62-196-86.eu-north-1.compute.amazonaws.com','backend', 'frontend' ]

ALLOWED_HOSTS = ['*']




CSRF_TRUSTED_ORIGINS = [
    "https://shopplus-frontend.vercel.app"
    "http://44.205.23.77",
    "http://ec2-44-205-23-77.compute-1.amazonaws.com",
    # "http://localhost", 
    # "http://127.0.0.1",
    "http://localhost:3000",
    "http://0.0.0.0:3000",

]


CORS_ALLOWED_ORIGINS = [
    "https://shopplus-frontend.vercel.app"
    "http://44.205.23.77",
    "http://ec2-44-205-23-77.compute-1.amazonaws.com",
    # 'http://localhost', 
    # 'http://127.0.0.1',
    "http://localhost:3000",
    "http://0.0.0.0:3000",
 
]


# Important for Nginx proxying
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = 'Lax'


AWS_QUERYSTRING_AUTH = True
         

# This is correct and covers all standard headers
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "origin",
    "user-agent",
    "dnt",
    "x-csrftoken",
    "x-requested-with",
]



# from .unfold_callbacks import (
#     environment_callback,
#     environment_title_prefix_callback,
#     dashboard_callback,

# )

# from django.templatetags.static import static
# from django.urls import reverse_lazy
# from django.utils.translation import gettext_lazy as _

# UNFOLD = {
#     "SITE_TITLE": "Admin | ShopLentic",
#     "SITE_HEADER": "ShopLentic Admin",
#     "SITE_SUBHEADER": "Manage Users and Access",
#     "SITE_URL": "/",
#     "SITE_ICON": {
#         "light": lambda request: static("icons/icon-light.svg"),
#         "dark": lambda request: static("icons/icon-dark.svg"),
#     },
#     "SITE_LOGO": {
#         "light": lambda request: static("logos/logo-light.PNG"),
#         "dark": lambda request: static("logos/logo-dark.svg"),
#     },
#     "SITE_SYMBOL": "person",  # Material icon
#     "SITE_FAVICONS": [
#         {
#             "rel": "icon",
#             "sizes": "32x32",
#             "type": "image/svg+xml",
#             "href": lambda request: static("favicons/favicon.svg"),
#         },
#     ],

#      "SITE_DROPDOWN": [
#         {
#             "icon": "diamond",
#             "title": _("ShopLentic"),
#             "link": "http://13.62.196.86",
#         },
#         # ...
#     ],

#       "SITE_SYMBOL": "speed",  # symbol from icon set
    
#     "SHOW_HISTORY": True,
#     "SHOW_VIEW_ON_SITE": True,
#     "SHOW_BACK_BUTTON": True,
#     "ENVIRONMENT": environment_callback,
#     "ENVIRONMENT_TITLE_PREFIX": environment_title_prefix_callback,
#     "DASHBOARD_CALLBACK": dashboard_callback,
#     "THEME": True,
#     "LOGIN": {
#         "image": lambda request: static("images/login-bg.jpg"),
#         "redirect_after": lambda request: reverse_lazy("admin:nextCart_user_changelist"),
#     },
#     "STYLES": [
#         lambda request: static("css/style.css"),
#     ],
#     "SCRIPTS": [
#         lambda request: static("js/script.js"),
#     ],
#     "BORDER_RADIUS": "8px",
#     "COLORS": {
#         "base": {
#             "50": "249 250 251",
#             "100": "243 244 246",
#             "200": "229 231 235",
#             "300": "209 213 219",
#             "400": "156 163 175",
#             "500": "107 114 128",
#             "600": "75 85 99",
#             "700": "55 65 81",
#             "800": "31 41 55",
#             "900": "17 24 39",
#             "950": "3 7 18",
#         },
#         "primary": {
#             "50": "240 249 255",
#             "100": "224 242 254",
#             "200": "186 230 253",
#             "300": "125 211 252",
#             "400": "56 189 248",
#             "500": "14 165 233",
#             "600": "2 132 199",
#             "700": "3 105 161",
#             "800": "7 89 133",
#             "900": "12 74 110",
#             "950": "8 47 73",
#         },
#         "font": {
#             "subtle-light": "var(--color-base-500)",
#             "subtle-dark": "var(--color-base-400)",
#             "default-light": "var(--color-base-600)",
#             "default-dark": "var(--color-base-300)",
#             "important-light": "var(--color-base-900)",
#             "important-dark": "var(--color-base-100)",
#         },
#     },
#     "EXTENSIONS": {
#         "modeltranslation": {
#             "flags": {
#                 "en": "🇬🇧",
#                 "bn": "🇧🇩",
#             },
#         },
#     },
#     "SIDEBAR": {
#         "show_search": True,
#         "show_all_applications": True,
#         "navigation": [
#             {
#                 "title": _("User Management"),
#                 "separator": True,
#                 "collapsible": True,
#                 "items": [
#                     {
#                         "title": _("Dashboard"),
#                         "icon": "dashboard",
#                         "link": reverse_lazy("admin:index"),
#                         "permission": lambda request: request.user.is_superuser,
#                     },
#                     {
#                         "title": _("Users"),
#                         "icon": "people",
#                         "link": reverse_lazy("admin:nextCart_user_changelist"),
#                         "permission": lambda request: request.user.is_staff,
#                     },
#                 ],
#             },
#         ],
#     },
#     "TABS": [
#         {
#             "models": [
#                 "nextCart.user",
#             ],
#             "items": [
#                 {
#                     "title": _("All Users"),
#                     "link": reverse_lazy("admin:nextCart_user_changelist"),
#                     "permission": lambda request: request.user.is_staff,
#                 },

        


#             ],
#         },
#     ],
# }







# At the end of your settings.py, add this conditional storage setup:

# ============================================================================
# STORAGE CONFIGURATION - Use S3 in production, local storage in development
# ============================================================================



# if DEBUG :
#     STORAGES = {
#     "default": {
#         "BACKEND": "django.core.files.storage.FileSystemStorage",
#     },
#     "staticfiles": {
#         "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
#     },
# }
#     MEDIA_URL = "/media/"
#     MEDIA_ROOT = os.path.join( BASE_DIR / 'media')
#     # STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] 
# else :
#     INSTALLED_APPS += ["storages"]
#     AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
#     AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
#     AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
#     AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "us-east-1")
#     AWS_DEFAULT_ACL = None
#     AWS_S3_FILE_OVERWRITE = False
#     AWS_QUERYSTRING_AUTH = False
#     AWS_S3_OBJECT_PARAMETERS = {
#     "CacheControl": "max-age=86400",
#     }
#     MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/media/"
#     STATIC_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/static/"
#     STORAGES = {
#         "default": {
#         "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
#         "OPTIONS": {
#             "location": "media",
#         },
#         },
#         "staticfiles": {
#         "BACKEND": "storages.backends.s3boto3.S3StaticStorage",
#         "OPTIONS": {
#             "location": "static",
#         },
#         },
#     }

# ============================================================================



if DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    INSTALLED_APPS += ["storages"]
    AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "us-east-1")
    
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False


    # AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_CUSTOM_DOMAIN = "d2jlzos2a8il9t.cloudfront.net"
    
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "location": "media",
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3StaticStorage",
            "OPTIONS": {
                "location": "static",
            },
        },
    }