# Generated by Django 5.1.4 on 2025-03-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquality',
            name='product',
        ),
    ]
