# Generated by Django 5.1.4 on 2025-03-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0002_remove_productquality_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='quality',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='quality',
            field=models.ManyToManyField(blank=True, related_name='variants', to='nextCart.productquality'),
        ),
    ]
