# Generated by Django 5.1.4 on 2025-03-09 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0003_remove_productvariant_quality_productvariant_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='nextCart.review'),
        ),
    ]
