# Generated by Django 5.1.4 on 2025-03-18 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0005_requestquote_specialoffer_product_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialoffer',
            name='description',
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='special_offers/'),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_offers', to='nextCart.product'),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
