# Generated by Django 5.1.4 on 2025-03-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0006_remove_specialoffer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
