# Generated by Django 5.1.4 on 2025-03-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0010_electronicsproduct_outdoorproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.ManyToManyField(blank=True,  related_name='ratings', to='nextCart.review'),
        ),
    ]
