# Generated by Django 5.1.4 on 2025-03-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0011_remove_product_rating_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.ManyToManyField(blank=True, null=True, related_name='ratings', to='nextCart.review'),
        ),
    ]
