# Generated by Django 5.1.4 on 2025-03-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0014_community_reviewcategory_review_community_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=50, unique=True)),
                ('order_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='sort_by',
            field=models.CharField(choices=[('newest', 'Newest'), ('oldest', 'Oldest'), ('highest-rating', 'Highest Rating'), ('lowest-rating', 'Lowest Rating'), ('most-helpful', 'Most Helpful')], default='newest', max_length=50),
        ),
    ]
