# Generated by Django 5.1.4 on 2025-03-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0016_review_helpful_votes_review_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_categories',
            field=models.CharField(choices=[('ALL', 'All Categories'), ('CLOTHES', 'Clothes and Wear'), ('HOME', 'Home Interiors'), ('ELECTRONICS', 'Electronics'), ('BEAUTY', 'Beauty & Health'), ('SPORTS', 'Sports & Outdoors')], default='ALL', max_length=20),
        ),
    ]
