# Generated by Django 5.1.4 on 2025-03-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0018_wishlist_product_variant_shippinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='en-US', max_length=10),
        ),
    ]
