# Generated by Django 5.1.4 on 2025-03-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0020_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
