# Generated by Django 5.1.4 on 2025-03-30 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0021_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nextCart.productvariant'),
        ),
    ]
