# Generated by Django 5.1.4 on 2025-03-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0022_productimage_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='default_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
