# Generated by Django 5.1.4 on 2025-03-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0024_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images_wishlist/'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='name',
            field=models.CharField(default='Wishlist', max_length=100),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
