# Generated by Django 5.1.4 on 2025-03-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0025_wishlist_color_wishlist_image_wishlist_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product_variant',
        ),
    ]
