# Generated by Django 5.1.4 on 2025-03-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0026_remove_wishlist_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
