# Generated by Django 5.1.4 on 2025-04-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0027_alter_wishlist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
