# Generated by Django 5.1.4 on 2025-05-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0029_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_variant',
            field=models.ManyToManyField(blank=True, related_name='product_variant_item', to='nextCart.productvariant'),
        ),
    ]
