# Generated by Django 5.1.4 on 2025-06-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0030_alter_orderitem_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquality',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Magenta', 'Magenta'), ('Maroon', 'Maroon'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Teal', 'Teal'), ('Lime', 'Lime'), ('Beige', 'Beige'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Violet', 'Violet'), ('Indigo', 'Indigo'), ('Turquoise', 'Turquoise'), ('Lavender', 'Lavender'), ('Crimson', 'Crimson'), ('Coral', 'Coral'), ('Peach', 'Peach'), ('Mint', 'Mint'), ('Ivory', 'Ivory'), ('Charcoal', 'Charcoal'), ('Burgundy', 'Burgundy'), ('Rose', 'Rose'), ('Emerald', 'Emerald'), ('Saffron', 'Saffron'), ('Azure', 'Azure')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productquality',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('2 Inches', '2 Inches'), ('6 x 8 inch', '6 x 8 inch'), ('8 x 11 inch', '8 x 11 inch'), ('7 x 9 inch', '7 x 9 inch'), ('9 x 12 inch', '9 x 12 inch'), ('10 x 15 inch', '10 x 15 inch')], max_length=100, null=True),
        ),
    ]
