# Generated by Django 5.1.4 on 2025-06-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0031_alter_productquality_color_alter_productquality_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquality',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('2 Inches', '2 Inches'), ('4 Inches', '4 Inches'), ('6 Inches', '6 Inches'), ('6 x 8 inch', '6 x 8 inch'), ('8 x 11 inch', '8 x 11 inch'), ('7 x 9 inch', '7 x 9 inch'), ('9 x 12 inch', '9 x 12 inch'), ('10 x 15 inch', '10 x 15 inch')], max_length=100, null=True),
        ),
    ]
