# Generated by Django 5.1.4 on 2025-07-15 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0033_product_care_instructions_product_materials_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
