# Generated by Django 5.1.4 on 2025-07-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0034_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productfeature',
            options={},
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productfeature',
            name='text',
        ),
        migrations.AddField(
            model_name='productfeature',
            name='feature',
            field=models.CharField(default='Slim Fit Design', max_length=200),
        ),
    ]
