# Generated by Django 5.1.4 on 2025-07-20 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0035_alter_product_options_alter_productfeature_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=200)),
                ('core', models.TextField(max_length=100)),
                ('origin', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='nextCart.product')),
            ],
        ),
    ]
