# Generated by Django 5.1.4 on 2025-07-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0041_alter_orderitem_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderItems',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='product',
            new_name='products',
        ),
    ]
