# Generated by Django 5.1.4 on 2025-07-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0042_rename_orderitem_orderitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='color',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='size',
            field=models.CharField(default='M', max_length=20),
        ),
    ]
