# Generated by Django 5.1.4 on 2025-07-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0043_orderitems_color_orderitems_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('apartment', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=50)),
                ('postalCode', models.IntegerField(max_length=20)),
                ('phone', models.IntegerField(max_length=20)),
                ('saveInfo', models.BooleanField()),
                ('shipping_method', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('overnight', 'Overnight')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
