# Generated by Django 5.1.4 on 2025-07-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0044_shippingaddress_order_shipping_cost_order_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='postalCode',
            field=models.IntegerField(),
        ),
    ]
