# Generated by Django 5.1.4 on 2025-07-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0045_alter_shippingaddress_postalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
