# Generated by Django 5.1.4 on 2025-07-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0046_alter_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
