# Generated by Django 5.1.4 on 2025-07-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0047_alter_shippingaddress_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
