# Generated by Django 5.1.4 on 2025-07-28 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0050_alter_shippingaddress_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='nextCart.order'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingaddress',
            unique_together={('order',)},
        ),
    ]
