# Generated by Django 5.1.4 on 2025-08-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0051_alter_shippingaddress_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='image',
            field=models.ImageField(default='image.png', upload_to='order_items/'),
        ),
    ]
