# Generated by Django 5.1.4 on 2025-08-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0052_orderitems_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uniqId',
            field=models.CharField(default='ORD001', max_length=20, unique=True),
        ),
    ]
