# Generated by Django 5.1.4 on 2025-08-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0054_alter_order_uniqid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uniqId',
            field=models.CharField(default='ORD001', max_length=20),
        ),
    ]
