# Generated by Django 5.1.4 on 2025-09-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0057_addressinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressinfo',
            old_name='isDefaults',
            new_name='isDefault',
        ),
    ]
