# Generated by Django 5.1.4 on 2025-09-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0058_rename_isdefaults_addressinfo_isdefault'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=10000)),
            ],
        ),
    ]
