# Generated by Django 5.1.4 on 2025-09-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0059_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter', models.BooleanField(blank=True, null=True)),
                ('smsMarketing', models.BooleanField(blank=True, null=True)),
                ('emailMarketing', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
