# Generated by Django 5.1.4 on 2025-09-24 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0060_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='nextCart.addressinfo'),
        ),
    ]
