# Generated by Django 5.1.4 on 2025-09-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0061_preferences_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressinfo',
            name='emailMarketing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='newsletter',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addressinfo',
            name='smsMarketing',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
