# Generated by Django 5.1.4 on 2025-09-26 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0062_addressinfo_emailmarketing_addressinfo_newsletter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
