# Generated by Django 5.1.4 on 2025-09-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0063_addressinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
