# Generated by Django 5.1.4 on 2025-09-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0065_alter_product_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
