# Generated by Django 5.1.4 on 2025-09-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0066_alter_product_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='save_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
