# Generated by Django 5.1.4 on 2025-09-28 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0067_product_save_price_product_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='save_price',
        ),
    ]
