# Generated by Django 5.1.4 on 2025-09-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0068_remove_product_save_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_ratings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
