# Generated by Django 5.1.4 on 2025-09-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0069_product_average_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_ratings',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
