# Generated by Django 5.1.4 on 2025-09-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0070_alter_product_average_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_ratings',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
