# Generated by Django 5.1.4 on 2025-10-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0071_alter_product_average_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicsproduct',
            name='image',
            field=models.ImageField(upload_to='electronics_product/images/'),
        ),
        migrations.AlterField(
            model_name='outdoorproduct',
            name='image',
            field=models.ImageField(upload_to='outdoor_product/images/ '),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_image/images/'),
        ),
        migrations.AlterField(
            model_name='productquality',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_images/images/'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='special_offer/images/'),
        ),
    ]
