# Generated by Django 5.1.4 on 2025-10-16 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0072_alter_electronicsproduct_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquality',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_quality', to='nextCart.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main_product/images/'),
        ),
    ]
