# Generated by Django 5.1.4 on 2025-10-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0073_productquality_product_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outdoorproduct',
            name='image',
            field=models.ImageField(upload_to='outdoor_product/images/'),
        ),
    ]
