# Generated by Django 5.1.4 on 2026-01-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0074_alter_outdoorproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='main_product/images/'),
        ),
    ]
