# Generated by Django 5.1.4 on 2026-01-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0075_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outdoorproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product_variant',
        ),
        migrations.RemoveField(
            model_name='specialoffer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='specialoffers',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ElectronicsProduct',
        ),
        migrations.DeleteModel(
            name='OutdoorProduct',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='SpecialOffer',
        ),
        migrations.DeleteModel(
            name='SpecialOffers',
        ),
    ]
