# Generated by Django 5.1.4 on 2026-01-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0076_remove_outdoorproduct_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
