# Generated by Django 5.1.4 on 2026-01-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0077_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productquality',
            name='custom_color_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productquality',
            name='custom_colors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productquality',
            name='custom_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
