# Generated by Django 5.1.4 on 2026-01-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0078_productquality_custom_color_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productquality',
            old_name='custom_colors',
            new_name='custom_color',
        ),
    ]
