# Generated by Django 5.1.4 on 2026-01-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0079_rename_custom_colors_productquality_custom_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
    ]
