# Generated by Django 5.1.4 on 2026-01-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0080_alter_cartitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='image',
            field=models.URLField(blank=True, default='https://via.placeholder.com/150', null=True),
        ),
    ]
