# Generated by Django 5.1.4 on 2026-02-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0081_alter_wishlist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='review-image'),
        ),
    ]
