# Generated by Django 5.1.4 on 2026-02-09 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0082_reviews_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='images',
        ),
    ]
