# Generated by Django 5.1.4 on 2026-02-16 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nextCart', '0086_reviews_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquality',
            name='custom_color_code',
        ),
        migrations.RemoveField(
            model_name='productquality',
            name='size_code',
        ),
    ]
